import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar'; // මෙහෙම වෙනස් කරන්න

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar /> {/* Navbar එක මෙතනට දාන්න */}
        {children}
      </body>
    </html>
  );
}